name: SkyFall
main: me.fromgate.skyfall.SkyFall
version: 0.1.0
author: fromgate, fromgate@gmail.com
softdepend: [Multiverse-Core,MultiWorld]
commands:
   skyfall:
      description: SkyFall configuration command 
      usage: 
           /skyfall help